package com.varna.automationengine.api.dto.response;

/**
 * Represents a structured, client-facing error response body.
 *
 * <p>This DTO (Data Transfer Object) is returned in the HTTP response body whenever
 * an error occurs. It is deliberately simple and contains only information that is
 * safe and useful to expose to an API client.
 *
 * <p><b>Why a dedicated DTO instead of a raw map or String?</b>
 * <ul>
 *   <li>Provides a consistent, typed contract — clients always know what fields to expect</li>
 *   <li>Jackson (Spring's JSON library) auto-serializes it without any extra config</li>
 *   <li>Easy to extend later (e.g. add a {@code details} list for field-level validation errors)</li>
 * </ul>
 *
 * <p><b>Example JSON output:</b>
 * <pre>
 * {
 *   "code": "PARSE_ERROR",
 *   "message": "Unable to parse the uploaded file as an OpenAPI specification.",
 *   "traceId": "550e8400-e29b-41d4-a716-446655440000",
 *   "timestamp": "2025-01-01T12:00:00Z"
 * }
 * </pre>
 *
 * <p>Using a Java {@code record} (Java 16+) gives us an immutable data class with
 * a canonical constructor, getters, {@code equals}, {@code hashCode}, and {@code toString}
 * automatically generated by the compiler — no boilerplate needed.
 *
 * @param code      a stable, machine-readable error code that clients can switch on
 *                  (e.g. {@code "PARSE_ERROR"}, {@code "FILE_TOO_LARGE"})
 * @param message   a human-readable description of what went wrong; safe to display in a UI
 * @param traceId   a unique request identifier — use this to find the corresponding log entries
 * @param timestamp ISO-8601 UTC timestamp of when the error was generated
 */
public record ErrorResponse(
        String code,
        String message,
        String traceId,
        String timestamp
) {

    /**
     * Convenience factory method for quickly building an ErrorResponse.
     *
     * <p>Example usage:
     * <pre>
     * ErrorResponse error = ErrorResponse.of("PARSE_ERROR", "Invalid spec", traceId);
     * </pre>
     *
     * @param code    the error code
     * @param message the human-readable message
     * @param traceId the request trace ID
     * @return a new {@code ErrorResponse} with the current UTC timestamp
     */
    public static ErrorResponse of(String code, String message, String traceId) {
        return new ErrorResponse(
                code,
                message,
                traceId,
                java.time.Instant.now().toString()
        );
    }
}